### ISSUE TITLE
什么时候完成剩下的部分，在线等～～

### ISSUE THREAD

**Issue by afredlyj** [code4craft/netty-learning#4]

**Comment by su-kaiyao** [comment]
我也是醉了...这个仓库没人维护了

**Comment by nesuk** [comment]
前面写得很好，期待作者更新，加油！

**Comment by welkineins** [comment]
期待更新，寫的真的不錯

**Comment by code4craft** [comment]
暂时重点不在这方面了，这个仓库应该是不会再维护了

**Comment by lishunli** [comment]
@nyzoupu 
嗯，已经失效，重新上传一份
[alibaba-dubbo-dependency.zip](https://github.com/alibaba/dubbo/files/310085/alibaba-dubbo-dependency.zip)
