### ISSUE TITLE
确实jar包

### ISSUE THREAD

**Issue by lqxion** [code4craft/netty-learning#6]
<dependency>
          <groupId>com.dianping</groupId>
          <artifactId>mocksocks-client</artifactId>
          <version>0.0.2-SNAPSHOT</version>
      </dependency>dianping?点评？是作者公司内部代码么？在maven库、osc上都没有收到！

**Comment by code4craft** [comment]
https://github.com/code4craft/mocksocks 你说的是这个项目吧，没有发布过maven，不过已经不维护了。
